# Generated by Django 4.2.2 on 2023-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Fecha', models.DateField()),
                ('Titulo', models.CharField(max_length=50)),
                ('Subtitulo', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=200)),
            ],
        ),
    ]
